# src/progonpy/domain/protocols.py
from __future__ import annotations
from typing import Protocol, Optional, runtime_checkable
from .models import TestReport


@runtime_checkable
class ModbusPort(Protocol):
    """Интерфейс Modbus-клиента"""
    def connect(self, config) -> bool: ...
    def disconnect(self) -> None: ...
    def read_registers(self, address: int, register: int, count: int) -> Optional[list[int]]: ...
    def write_register(self, address: int, register: int, value: int) -> bool: ...
    def write_registers(self, address: int, register: int, values: list[int]) -> bool: ...


@runtime_checkable  
class DeviceTestPort(Protocol):
    """Расширенный интерфейс для тестирования"""
    # Наследуем базовые методы + добавляем специфичные
    def read_registers(self, address: int, register: int, count: int) -> Optional[list[int]]: ...
    def write_register(self, address: int, register: int, value: int) -> bool: ...
    def write_registers(self, address: int, register: int, values: list[int]) -> bool: ...
    
    # Опционально: методы для сложных операций
    def write_float(self, address: int, register: int, value: float) -> bool: ...