from __future__ import annotations

from typing import Protocol

from .models import SerialConfig


class ModbusPort(Protocol):
    def connect(self, config: SerialConfig) -> bool: ...
    def disconnect(self) -> None: ...
    def read_registers(self, address: int, register: int, count: int) -> list[int] | None: ...
    def write_register(self, address: int, register: int, value: int) -> bool: ...
    def write_registers(self, address: int, register: int, values: list[int]) -> bool: ...
